apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: stuffie-collection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: gitlab-registry-secret
      containers:
        - name: frontend
          image: 192.168.40.246:5050/ikuchans/stuffie-collection-app/frontend:latest
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
