apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: stuffie-collection
type: Opaque
stringData:
  MINIO_ROOT_USER: stuffie-admin
  # 本番運用するなら実際に使う強いパスワードに変更すること
  MINIO_ROOT_PASSWORD: stuffie-minio-password-change-me
